baseURL = "https://apurvt.github.io/"
languageCode = "en-us"
#title = "Apurv Tiwari"
theme = "hello-friend-ng"
publishDir = "apurvt.github.io"

#buildDrafts  = false
#buildFuture  = false
#canonifyURLs = true

#enableRobotsTXT = true
#enableGitInfo   = true
#enableEmoji     = true
#enableMissingTranslationPlaceholders = false
#disableRSS     = false
#disableSitemap = false
#disable404     = false
#disableHugoGeneratorInject = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Metadata mostly used in document's head
  description = "Homepage and blog by Apurv Tiwari"
  keywords = "homepage, blog, science, informatics, development, programming, cybersecurity"
  images = [""]
  homeSubtitle = "Cyber Security Engineer"


  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/ApurvT/ApurvT.github.io"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.logo]]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/ApurvTiwari13"

  [[params.social]]
    name = "email"
    url  = "mailto:apurvraja@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/ApurvT/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/apurvraja/"

  #[[params.social]]
  #  name = "keybase"
  #  url  = ""

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Apurv Tiwari"
    #subtitle = "Cyber Security Engineer"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
     logoText = "$ cd /home/"
     logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "me"
    name       = "Me"
    url        = "me/"
  [[menu.main]]
    identifier = "posts"
    name       = "Articles"
    url        = "posts/"
  [[menu.main]]
    identifier = "writeups"
    name       = "Write Ups"
    url        = "writeups/"